<?php

class PDF extends FPDF{
		function clausulas(){
				$this->SetXY(10, 17);
				$this->SetFont('Arial','B',8);
				$this->MultiCell(190, 4, utf8_decode('CONTRATO DE COMPRA VENTA AL CONTADO DE MOBILIARIO DE LINEA QUE CELEBRAN "EL PROVEEDOR" Y EL "CONSUMIDOR" CUYOS NOMBRES Y DATOS CONSTAN EN LA CARATULA DE ESTE CONTRATO COMO PARTE INTEGRAL DEL MISMO, SUJETANDOSE AL TENOR SIGUIENTE:'), 0);
				$this -> Ln();
				$this->Cell(190,5,'CLAUSULAS',0,1,'C');
				$this -> Ln();
				$this->SetFont('Arial','',8);
				$this->MultiCell(190, 4, utf8_decode('PRIMERA.- EL OBJETO DEL PRESENTE CONTRATO ES LA COMPRAVENTA DEL MOBILIARIO DESCRITO EN LA CARÁTULA.'), 0);
				$this -> Ln();
				$this->MultiCell(190, 4, utf8_decode('SEGUNDA.- "EL PROVEEDOR" SE OBLIGA A ENTREGAR EL MOBILIARIO OBJETO DEL PRESENTE CONTRATO EN EL DOMICILIO INDICADO EN LA CARÁTULA SEGÚN LO SOLICITADO POR EL "CONSUMIDOR" "EL PROVEEDOR" SERÁ RESPONSABLE DE LA PÉRDIDA, DAÑO O DETERIORO QUE SUFRA EL MOBILIARIO EN CASO DE QUE ESTE SE OBLIGUE A ENTREGARLO EN EL DOMICILIO DEL CONSUMIDOR.'), 0);
				$this -> Ln();
				$this->MultiCell(190, 4, utf8_decode('EN CASO DE QUE "EL CONSUMIDOR" RECOJA EL MOBILIARIO EN EL DOMICILIO DEL PROVEEDOR A PARTIR DE ESE MOMENTO SERÁ RESPONSABLE DE LA PERDIDA, DAÑO O DETERIORO QUE SUFRA EL MOBILIARIO'), 0);
				$this -> Ln();
				$this->MultiCell(190, 4, utf8_decode('TERCERA.- "EL PROVEEDOR" SE OBLIGA A INSTALAR EL MOBILIARIO OBJETO DE ESTE CONTRATO DE ACUERDO A LO SOLICITADO POR "EL CONSUMIDOR" EN LA FECHA ESTABLECIDA EN LA CARÁTULA DEL MISMO.'), 0);
				$this -> Ln();
				$this->MultiCell(190, 4, utf8_decode('CUARTA.- EL MOBILIARIO OBJETO DEL PRESENTE CONTRATO TIENE UNA GARANTIA DE 60 DÍAS NATURALES CONTADOS A PARTIR DE LA FECHA DE ENTREGA DEL MISMO, PARA HACER EFECTIVA ESTA GARANTIA, "EL CONSUMIDOR" DEBERÁ ACUDIR AL DOMICILIO DEL PROVEEDOR PRESENTANDO POR ESCRITO EL CONCEPTO DE LA RECLAMACIÓN, "EL PROVEEDOR" DEBERÁ DAR CUMPLIMIENTO A LA GARANTIA DENTRO DE LOS 5 DÍAS NATURALES SIGUIENTES, SIN COSTO ALGUNO PARA "EL CONSUMIDOR".'), 0);
				$this -> Ln();
				$this->MultiCell(190, 4, utf8_decode('QUINTA.- LOS CONTRATANTES ESTAN DE ACUERDO EN QUE EL INCUMPLIMIENTO DE CUALQUIERA DE LAS OBLIGACIONES CONTENIDAS EN EL PRESENTE CONTRATO ORIGINARÁ A CARGO DEL RESPONSABLE UNA PENA CONVENCIONAL EQUIVALENTE AL 15% DEL IMPORTE TOTAL DE LA OPERACIÓN. EN CASO DE SER "EL PROVEEDOR" QUIEN INCUMPLA ADEMAS DE LA PENA CONVENCIONAL ANTES CITADA, DEBERÁ DEVOLVER LAS CANTIDADES PAGADAS POR ADELANTADO.'), 0);
				$this -> Ln();
				$this->MultiCell(190, 4, utf8_decode('SEXTA.- "EL PROVEEDOR" SE OBLIGA A ENTREGAR AL CONSUMIDOR NOTA, FACTURA O COMPROBANTE POR CONCEPTO DE ANTICIPO, ASÍ COMO AL MOMENTO DE QUE ÉSTE LIQUIDE EL PRECIO, ESPECIFICANDO EN CADA CASO EL CONCEPTO POR EL CUAL RECIBE LOS PAGOS.'), 0);
				$this -> Ln();
				$this->MultiCell(190, 4, utf8_decode('SEPTIMA.- "EL CONSUMIDOR" PODRÁ FORMULAR POR ESCRITO CUALQUIER RECLAMACIÓN, DEVOLUCIÓN Y/O REEMBOLSO RELACIONADO CON EL MOBILIARIO OBJETO DEL PRESENTE CONTRATO EN EL DOMICILIO Y EN EL HORARIO SEÑALADOS EN LA CARÁTULA DE ESTE CONTRATO DE CONFORMIDAD CON LO SEÑALADO EN LOS ARTÍCULOS 82, 92 Y 93 DE LA LEY FEDERAL DE PROTECCION AL CONSUMIDOR.'), 0);
				$this -> Ln();
				$this->MultiCell(190, 4, utf8_decode('OCTAVA.- LA PROCURADURÍA FEDERAL DEL CONSUMIDOR ES COMPETENTE EN LA VÍA ADMINISTRATIVA PARA RESOLVER CUALQUIER CONTROVERSIA QUE SE SUSCITE SOBRE LA INTERPRETACION O CUMPLIMIENTO DEL PRESENTE CONTRATO. SIN PERJUICIO DE LO ANTERIOR, LAS PARTES SE SOMETEN A LA JURISDICCIÓN DE LOS TRIBUNALES COMPETENTES DE LA CIUDAD DE EDO. DE MEX., RENUNCIANDO EXPRESAMENTE A CUALQUIER OTRA JURISDICCIÓN QUE PUDIERA CORRESPONDERLES POR RAZÓN DE SUS DOMICILIOS PRESENTES O FUTUROS O POR CUALQUIER OTRA RAZÓN.'), 0);
				$this -> Ln();
				$this->MultiCell(190, 4, utf8_decode('EL MODELO DEL PRESENTE CONTRATO DE ADHESIÓN FUE REGISTRADO EN EL REGISTRO PÚBLICO DE CONTRATOS DE ADHESIÓN DE LA PROCURADURIA FEDERAL DEL CONSUMIDOR BAJO EL NÚMERO 4205-2009 DE FECHA 19/06/09 CUALQUIER VARIACIÓN DEL PRESENTE CONTRATO EN PERJUICIO DEL CONSUMIDOR FRENTE AL CONTRATO DE ADHESIÓN REGISTRADO SE TENDRÁ POR NO PUESTA.'), 0);
				
				$posY = $this-> GetY();
				$this->SetXY(38, $posY + 40);
				$this->Cell(47.5,5,'EL PROVEEDOR',0,0,'C');
				$this->Cell(38,5,'',0,0,'C');
				$this->Cell(47.5,5,'EL CONSUMIDOR',0,1,'C');
				}
		}
//$pdf=new PDF();
$pdf = new PDF('P','mm','Letter');
$pdf->AddPage();
$pdf->clausulas();
$pdf->Output();
?>